# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
